[package]
name = "concu_cmd"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "3.1.5"
rayon = "1.5.2"
rand = "0.8.5"
thread-id = "4.0.0"
